// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApi.Database.Context;

#nullable disable

namespace MinimalApi.Database.Migrations.Joker
{
    [DbContext(typeof(JokerContext))]
    partial class JokerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MinimalApi.Common.Models.Joker", b =>
                {
                    b.Property<string>("JokerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JokeDay")
                        .HasColumnType("datetime2");

                    b.HasKey("JokerName", "CreatedDate");

                    b.ToTable("Jokers");
                });
#pragma warning restore 612, 618
        }
    }
}
